---
# tasks file for nainterceptor.common

# Change Root
- name: Change root password
  user: name=root password="{{ root_password }}"
  when: root_password|default(None) != None

# Upgrade
- name: "Upgrade all packages"
  yum: name=* state=latest
  when: ansible_distribution == 'CentOS'

- name: "Update APT package cache"
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Debian'

- name: "Upgrade APT to the latest packages"
  apt: upgrade=safe
  when: ansible_distribution == 'Debian'

#Configure SSH
- name: "Configure sshd"
  template: src=../files/{{ ansible_distribution }}/sshd_config.j2 dest=/etc/ssh/sshd_config
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Debian'
  notify:
    - "Restart sshd"

- name: "Install standard packages"
  yum: name={{ item }} state=present
  when: ansible_distribution == 'CentOS'
  with_items:
    - sudo
    - epel-release
    - tar
    - unzip

- name: "Install standard packages"
  apt: name={{ item }} state=present
  when: ansible_distribution == 'Debian'
  with_items:
    - sudo
